language: ruby
rvm:
  - 2.1.5
script: bin/rake test:all
deploy:
  provider: heroku
  app: artisanassistant
  api_key:
    secure: x0J2x8LVfsU5LNw9EFz7XcXIFRUIDigcAjzVV6AXS5+B6fEieBJZdBKmZTE2C7YL5kJyVJC1GuE2TcA+Hn0lF7omoJ8YVc1DMrNSDjCCz17MS74v/Op3ei9derG57joUegTp3i2hxxPm2z59jj5OruPz2jUjUg2GmfvFQBPcEF4=
  run:
    - "bin/rake db:migrate"
    - restart
